-- ERP Almacen - Resurtido y traspasos entre tiendas
-- Documentacion IA: Codex GPT-5
-- Fecha: 2026-07-11
-- Estado: propuesta de DDL, NO ejecutar sin respaldo externo y autorizacion.
-- Alcance: solicitudes de resurtido, envio/transito, recepcion y diferencias.

CREATE TABLE IF NOT EXISTS erp_inventario_politicas_almacen_sku (
  id_politica_almacen_sku INT NOT NULL AUTO_INCREMENT,
  id_almacen INT NOT NULL,
  id_sku_erp BIGINT NOT NULL,
  stock_minimo DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  stock_maximo DECIMAL(18,6) NULL,
  punto_reorden DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_sugerida DECIMAL(18,6) NULL,
  dias_cobertura_objetivo INT NOT NULL DEFAULT 0,
  prioridad VARCHAR(30) NOT NULL DEFAULT 'normal',
  estatus VARCHAR(30) NOT NULL DEFAULT 'activa',
  observaciones TEXT NULL,
  creado_por INT NULL,
  actualizado_por INT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion DATETIME NULL,
  PRIMARY KEY (id_politica_almacen_sku),
  UNIQUE KEY uk_inv_politica_almacen_sku (id_almacen, id_sku_erp),
  KEY idx_inv_politica_sku (id_sku_erp),
  KEY idx_inv_politica_estatus (estatus),
  CONSTRAINT fk_inv_pol_almacen FOREIGN KEY (id_almacen) REFERENCES erp_almacenes (id_almacen),
  CONSTRAINT fk_inv_pol_sku FOREIGN KEY (id_sku_erp) REFERENCES erp_catalogo_skus (id_sku)
);

CREATE TABLE IF NOT EXISTS erp_almacen_resurtidos (
  id_resurtido_almacen INT NOT NULL AUTO_INCREMENT,
  folio VARCHAR(60) NOT NULL,
  tipo_documento VARCHAR(30) NOT NULL DEFAULT 'resurtido_tienda',
  id_almacen_solicitante INT NOT NULL,
  id_almacen_origen INT NULL,
  id_almacen_transito INT NULL,
  estatus VARCHAR(40) NOT NULL DEFAULT 'borrador',
  prioridad VARCHAR(30) NOT NULL DEFAULT 'normal',
  origen_solicitud VARCHAR(40) NOT NULL DEFAULT 'manual',
  fecha_solicitud DATETIME NULL,
  fecha_autorizacion DATETIME NULL,
  fecha_preparacion DATETIME NULL,
  fecha_envio DATETIME NULL,
  fecha_recepcion DATETIME NULL,
  fecha_cierre DATETIME NULL,
  solicitado_por INT NULL,
  autorizado_por INT NULL,
  preparado_por INT NULL,
  enviado_por INT NULL,
  recibido_por INT NULL,
  cerrado_por INT NULL,
  observaciones TEXT NULL,
  motivo_cancelacion TEXT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion DATETIME NULL,
  PRIMARY KEY (id_resurtido_almacen),
  UNIQUE KEY uk_alm_resurtido_folio (folio),
  KEY idx_alm_resurtido_solicitante (id_almacen_solicitante),
  KEY idx_alm_resurtido_origen (id_almacen_origen),
  KEY idx_alm_resurtido_transito (id_almacen_transito),
  KEY idx_alm_resurtido_estatus (estatus),
  KEY idx_alm_resurtido_fecha (fecha_registro),
  CONSTRAINT fk_res_alm_solicitante FOREIGN KEY (id_almacen_solicitante) REFERENCES erp_almacenes (id_almacen),
  CONSTRAINT fk_res_alm_origen FOREIGN KEY (id_almacen_origen) REFERENCES erp_almacenes (id_almacen),
  CONSTRAINT fk_res_alm_transito FOREIGN KEY (id_almacen_transito) REFERENCES erp_almacenes (id_almacen)
);

CREATE TABLE IF NOT EXISTS erp_almacen_resurtido_detalle (
  id_resurtido_detalle INT NOT NULL AUTO_INCREMENT,
  id_resurtido_almacen INT NOT NULL,
  id_sku_erp BIGINT NOT NULL,
  id_producto INT NULL,
  sku VARCHAR(120) NULL,
  nombre_producto VARCHAR(255) NULL,
  unidad_base VARCHAR(40) NULL,
  cantidad_solicitada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_autorizada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_preparada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_enviada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_recibida DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_diferencia DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  estatus VARCHAR(40) NOT NULL DEFAULT 'pendiente',
  motivo_rechazo TEXT NULL,
  observaciones TEXT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion DATETIME NULL,
  PRIMARY KEY (id_resurtido_detalle),
  KEY idx_res_det_resurtido (id_resurtido_almacen),
  KEY idx_res_det_sku (id_sku_erp),
  KEY idx_res_det_estatus (estatus),
  CONSTRAINT fk_res_det_resurtido FOREIGN KEY (id_resurtido_almacen) REFERENCES erp_almacen_resurtidos (id_resurtido_almacen),
  CONSTRAINT fk_res_det_sku FOREIGN KEY (id_sku_erp) REFERENCES erp_catalogo_skus (id_sku)
);

CREATE TABLE IF NOT EXISTS erp_almacen_resurtido_preparacion (
  id_resurtido_preparacion INT NOT NULL AUTO_INCREMENT,
  id_resurtido_almacen INT NOT NULL,
  id_resurtido_detalle INT NOT NULL,
  id_existencia_origen INT NOT NULL,
  id_inventario_unidad INT NULL,
  id_almacen_origen INT NOT NULL,
  ubicacion_origen_id INT NULL,
  id_sku_erp BIGINT NOT NULL,
  lote VARCHAR(150) NULL,
  fecha_caducidad DATE NULL,
  cantidad_preparada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_unidad_antes DECIMAL(18,6) NULL,
  cantidad_unidad_despues DECIMAL(18,6) NULL,
  estado_fisico_unidad VARCHAR(30) NULL,
  estatus VARCHAR(40) NOT NULL DEFAULT 'preparada',
  preparado_por INT NULL,
  fecha_preparacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observaciones TEXT NULL,
  PRIMARY KEY (id_resurtido_preparacion),
  KEY idx_res_prep_resurtido (id_resurtido_almacen),
  KEY idx_res_prep_detalle (id_resurtido_detalle),
  KEY idx_res_prep_existencia (id_existencia_origen),
  KEY idx_res_prep_unidad (id_inventario_unidad),
  KEY idx_res_prep_sku (id_sku_erp),
  CONSTRAINT fk_res_prep_resurtido FOREIGN KEY (id_resurtido_almacen) REFERENCES erp_almacen_resurtidos (id_resurtido_almacen),
  CONSTRAINT fk_res_prep_detalle FOREIGN KEY (id_resurtido_detalle) REFERENCES erp_almacen_resurtido_detalle (id_resurtido_detalle),
  CONSTRAINT fk_res_prep_existencia FOREIGN KEY (id_existencia_origen) REFERENCES erp_inventario_existencias (id_existencia_inventario),
  CONSTRAINT fk_res_prep_unidad FOREIGN KEY (id_inventario_unidad) REFERENCES erp_inventario_unidades (id_inventario_unidad),
  CONSTRAINT fk_res_prep_almacen FOREIGN KEY (id_almacen_origen) REFERENCES erp_almacenes (id_almacen),
  CONSTRAINT fk_res_prep_sku FOREIGN KEY (id_sku_erp) REFERENCES erp_catalogo_skus (id_sku)
);

CREATE TABLE IF NOT EXISTS erp_almacen_resurtido_envios (
  id_resurtido_envio INT NOT NULL AUTO_INCREMENT,
  id_resurtido_almacen INT NOT NULL,
  id_resurtido_preparacion INT NOT NULL,
  id_movimiento_salida INT NULL,
  id_movimiento_transito_entrada INT NULL,
  id_existencia_transito INT NULL,
  id_inventario_unidad INT NULL,
  cantidad_enviada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  estatus VARCHAR(40) NOT NULL DEFAULT 'enviado',
  enviado_por INT NULL,
  fecha_envio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observaciones TEXT NULL,
  PRIMARY KEY (id_resurtido_envio),
  KEY idx_res_env_resurtido (id_resurtido_almacen),
  KEY idx_res_env_preparacion (id_resurtido_preparacion),
  KEY idx_res_env_salida (id_movimiento_salida),
  KEY idx_res_env_transito (id_existencia_transito),
  KEY idx_res_env_unidad (id_inventario_unidad),
  CONSTRAINT fk_res_env_resurtido FOREIGN KEY (id_resurtido_almacen) REFERENCES erp_almacen_resurtidos (id_resurtido_almacen),
  CONSTRAINT fk_res_env_preparacion FOREIGN KEY (id_resurtido_preparacion) REFERENCES erp_almacen_resurtido_preparacion (id_resurtido_preparacion),
  CONSTRAINT fk_res_env_mov_salida FOREIGN KEY (id_movimiento_salida) REFERENCES erp_inventario_movimientos (id_movimiento_inventario),
  CONSTRAINT fk_res_env_mov_transito FOREIGN KEY (id_movimiento_transito_entrada) REFERENCES erp_inventario_movimientos (id_movimiento_inventario),
  CONSTRAINT fk_res_env_existencia_transito FOREIGN KEY (id_existencia_transito) REFERENCES erp_inventario_existencias (id_existencia_inventario),
  CONSTRAINT fk_res_env_unidad FOREIGN KEY (id_inventario_unidad) REFERENCES erp_inventario_unidades (id_inventario_unidad)
);

CREATE TABLE IF NOT EXISTS erp_almacen_resurtido_recepciones (
  id_resurtido_recepcion INT NOT NULL AUTO_INCREMENT,
  id_resurtido_almacen INT NOT NULL,
  id_resurtido_envio INT NOT NULL,
  id_almacen_destino INT NOT NULL,
  ubicacion_destino_id INT NULL,
  id_movimiento_transito_salida INT NULL,
  id_movimiento_entrada_destino INT NULL,
  id_existencia_destino INT NULL,
  id_inventario_unidad INT NULL,
  lote_recibido VARCHAR(150) NULL,
  fecha_caducidad_recibida DATE NULL,
  cantidad_recibida DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  estatus VARCHAR(40) NOT NULL DEFAULT 'recibida',
  recibido_por INT NULL,
  fecha_recepcion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observaciones TEXT NULL,
  PRIMARY KEY (id_resurtido_recepcion),
  KEY idx_res_rec_resurtido (id_resurtido_almacen),
  KEY idx_res_rec_envio (id_resurtido_envio),
  KEY idx_res_rec_destino (id_almacen_destino),
  KEY idx_res_rec_existencia (id_existencia_destino),
  KEY idx_res_rec_unidad (id_inventario_unidad),
  CONSTRAINT fk_res_rec_resurtido FOREIGN KEY (id_resurtido_almacen) REFERENCES erp_almacen_resurtidos (id_resurtido_almacen),
  CONSTRAINT fk_res_rec_envio FOREIGN KEY (id_resurtido_envio) REFERENCES erp_almacen_resurtido_envios (id_resurtido_envio),
  CONSTRAINT fk_res_rec_almacen FOREIGN KEY (id_almacen_destino) REFERENCES erp_almacenes (id_almacen),
  CONSTRAINT fk_res_rec_mov_transito FOREIGN KEY (id_movimiento_transito_salida) REFERENCES erp_inventario_movimientos (id_movimiento_inventario),
  CONSTRAINT fk_res_rec_mov_entrada FOREIGN KEY (id_movimiento_entrada_destino) REFERENCES erp_inventario_movimientos (id_movimiento_inventario),
  CONSTRAINT fk_res_rec_existencia FOREIGN KEY (id_existencia_destino) REFERENCES erp_inventario_existencias (id_existencia_inventario),
  CONSTRAINT fk_res_rec_unidad FOREIGN KEY (id_inventario_unidad) REFERENCES erp_inventario_unidades (id_inventario_unidad)
);

CREATE TABLE IF NOT EXISTS erp_almacen_resurtido_diferencias (
  id_resurtido_diferencia INT NOT NULL AUTO_INCREMENT,
  id_resurtido_almacen INT NOT NULL,
  id_resurtido_detalle INT NULL,
  id_resurtido_envio INT NULL,
  id_resurtido_recepcion INT NULL,
  tipo_diferencia VARCHAR(40) NOT NULL,
  severidad VARCHAR(30) NOT NULL DEFAULT 'media',
  id_sku_erp BIGINT NULL,
  id_inventario_unidad INT NULL,
  cantidad_esperada DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_recibida DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  cantidad_diferencia DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  lote_esperado VARCHAR(150) NULL,
  lote_recibido VARCHAR(150) NULL,
  fecha_caducidad_esperada DATE NULL,
  fecha_caducidad_recibida DATE NULL,
  estatus VARCHAR(40) NOT NULL DEFAULT 'abierta',
  accion_sugerida VARCHAR(80) NULL,
  accion_tomada TEXT NULL,
  registrado_por INT NULL,
  resuelto_por INT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_resolucion DATETIME NULL,
  observaciones TEXT NULL,
  PRIMARY KEY (id_resurtido_diferencia),
  KEY idx_res_dif_resurtido (id_resurtido_almacen),
  KEY idx_res_dif_detalle (id_resurtido_detalle),
  KEY idx_res_dif_envio (id_resurtido_envio),
  KEY idx_res_dif_recepcion (id_resurtido_recepcion),
  KEY idx_res_dif_tipo (tipo_diferencia),
  KEY idx_res_dif_estatus (estatus),
  KEY idx_res_dif_sku (id_sku_erp),
  KEY idx_res_dif_unidad (id_inventario_unidad),
  CONSTRAINT fk_res_dif_resurtido FOREIGN KEY (id_resurtido_almacen) REFERENCES erp_almacen_resurtidos (id_resurtido_almacen),
  CONSTRAINT fk_res_dif_detalle FOREIGN KEY (id_resurtido_detalle) REFERENCES erp_almacen_resurtido_detalle (id_resurtido_detalle),
  CONSTRAINT fk_res_dif_envio FOREIGN KEY (id_resurtido_envio) REFERENCES erp_almacen_resurtido_envios (id_resurtido_envio),
  CONSTRAINT fk_res_dif_recepcion FOREIGN KEY (id_resurtido_recepcion) REFERENCES erp_almacen_resurtido_recepciones (id_resurtido_recepcion),
  CONSTRAINT fk_res_dif_sku FOREIGN KEY (id_sku_erp) REFERENCES erp_catalogo_skus (id_sku),
  CONSTRAINT fk_res_dif_unidad FOREIGN KEY (id_inventario_unidad) REFERENCES erp_inventario_unidades (id_inventario_unidad)
);
