-- ERP Almacen - Preparacion/Empaque de presentaciones
-- Clave: ALM-PREP-001
-- Estado: propuesta, NO ejecutado.
-- Requiere respaldo externo y autorizacion antes de aplicar.

CREATE TABLE IF NOT EXISTS erp_almacen_preparaciones (
  id_preparacion_almacen INT NOT NULL AUTO_INCREMENT,
  folio VARCHAR(60) NOT NULL,
  id_almacen INT NOT NULL,
  id_sku_base BIGINT NOT NULL,
  id_sku_presentacion BIGINT NOT NULL,
  id_sku_presentacion_regla BIGINT NULL,
  estatus VARCHAR(30) NOT NULL DEFAULT 'borrador',
  fecha_preparacion DATETIME NULL,
  unidades_preparadas INT NOT NULL DEFAULT 0,
  cantidad_base_consumida DECIMAL(18,6) NOT NULL DEFAULT 0,
  merma_porcentaje DECIMAL(8,4) NOT NULL DEFAULT 0,
  observaciones TEXT NULL,
  creado_por INT NULL,
  confirmado_por INT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion DATETIME NULL,
  PRIMARY KEY (id_preparacion_almacen),
  UNIQUE KEY uk_almacen_preparacion_folio (folio),
  KEY idx_almacen_preparacion_almacen (id_almacen),
  KEY idx_almacen_preparacion_sku_base (id_sku_base),
  KEY idx_almacen_preparacion_sku_presentacion (id_sku_presentacion),
  KEY idx_almacen_preparacion_estatus (estatus),
  KEY idx_almacen_preparacion_fecha (fecha_preparacion),
  CONSTRAINT fk_almacen_preparacion_sku_base FOREIGN KEY (id_sku_base) REFERENCES erp_catalogo_skus (id_sku),
  CONSTRAINT fk_almacen_preparacion_sku_presentacion FOREIGN KEY (id_sku_presentacion) REFERENCES erp_catalogo_skus (id_sku),
  CONSTRAINT fk_almacen_preparacion_regla FOREIGN KEY (id_sku_presentacion_regla) REFERENCES erp_catalogo_sku_presentaciones (id_sku_presentacion_regla)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS erp_almacen_preparacion_consumos (
  id_preparacion_consumo INT NOT NULL AUTO_INCREMENT,
  id_preparacion_almacen INT NOT NULL,
  id_existencia_inventario INT NOT NULL,
  id_sku_base BIGINT NOT NULL,
  id_almacen INT NOT NULL,
  ubicacion_id INT NULL,
  lote VARCHAR(150) NULL,
  fecha_caducidad DATE NULL,
  cantidad_consumida DECIMAL(18,6) NOT NULL,
  costo_unitario DECIMAL(12,4) NOT NULL DEFAULT 0,
  costo_total DECIMAL(12,4) NOT NULL DEFAULT 0,
  id_movimiento_salida INT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_preparacion_consumo),
  KEY idx_prep_consumo_preparacion (id_preparacion_almacen),
  KEY idx_prep_consumo_existencia (id_existencia_inventario),
  KEY idx_prep_consumo_sku_base (id_sku_base),
  KEY idx_prep_consumo_almacen (id_almacen),
  KEY idx_prep_consumo_lote (lote, fecha_caducidad),
  KEY idx_prep_consumo_movimiento (id_movimiento_salida),
  CONSTRAINT fk_prep_consumo_preparacion FOREIGN KEY (id_preparacion_almacen) REFERENCES erp_almacen_preparaciones (id_preparacion_almacen),
  CONSTRAINT fk_prep_consumo_existencia FOREIGN KEY (id_existencia_inventario) REFERENCES erp_inventario_existencias (id_existencia_inventario),
  CONSTRAINT fk_prep_consumo_sku_base FOREIGN KEY (id_sku_base) REFERENCES erp_catalogo_skus (id_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS erp_almacen_preparacion_resultados (
  id_preparacion_resultado INT NOT NULL AUTO_INCREMENT,
  id_preparacion_almacen INT NOT NULL,
  id_preparacion_consumo INT NULL,
  id_existencia_inventario INT NOT NULL,
  id_sku_presentacion BIGINT NOT NULL,
  id_almacen INT NOT NULL,
  ubicacion_id INT NULL,
  lote VARCHAR(150) NULL,
  fecha_caducidad DATE NULL,
  unidades_preparadas INT NOT NULL,
  factor_salida_base DECIMAL(18,6) NOT NULL,
  cantidad_base_equivalente DECIMAL(18,6) NOT NULL,
  costo_unitario DECIMAL(12,4) NOT NULL DEFAULT 0,
  costo_total DECIMAL(12,4) NOT NULL DEFAULT 0,
  genera_etiquetas TINYINT(1) NOT NULL DEFAULT 0,
  etiquetas_generadas INT NOT NULL DEFAULT 0,
  id_movimiento_entrada INT NULL,
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_preparacion_resultado),
  KEY idx_prep_resultado_preparacion (id_preparacion_almacen),
  KEY idx_prep_resultado_consumo (id_preparacion_consumo),
  KEY idx_prep_resultado_existencia (id_existencia_inventario),
  KEY idx_prep_resultado_sku_presentacion (id_sku_presentacion),
  KEY idx_prep_resultado_almacen (id_almacen),
  KEY idx_prep_resultado_lote (lote, fecha_caducidad),
  KEY idx_prep_resultado_movimiento (id_movimiento_entrada),
  CONSTRAINT fk_prep_resultado_preparacion FOREIGN KEY (id_preparacion_almacen) REFERENCES erp_almacen_preparaciones (id_preparacion_almacen),
  CONSTRAINT fk_prep_resultado_consumo FOREIGN KEY (id_preparacion_consumo) REFERENCES erp_almacen_preparacion_consumos (id_preparacion_consumo),
  CONSTRAINT fk_prep_resultado_existencia FOREIGN KEY (id_existencia_inventario) REFERENCES erp_inventario_existencias (id_existencia_inventario),
  CONSTRAINT fk_prep_resultado_sku_presentacion FOREIGN KEY (id_sku_presentacion) REFERENCES erp_catalogo_skus (id_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
